schema-version = 2

[defaults]
runtime = "python"

[packages.s3tables-table-manager]
path = "packages/s3tables-table-manager"
artifacts.s3tables-table-manager = { type = "lambda", build = "mise run build-lambda s3tables-table-manager" }
